# m1_poly_act.py

import json
from pathlib import Path
import torch
import torch.nn as nn

class PolyGelu(nn.Module):
    """
    A PyTorch module that implements a polynomial approximation of the GELU
    activation function, based on parameters from a JSON file.

    The function is defined in three parts:
    1. A constant value (0.0) for x < -4.
    2. A polynomial of order N for -4 <= x <= 4.
    3. A linear function (y=x) for x > 4.
    """
    def __init__(self, json_path: str):
        """
        Initializes the module by loading and parsing the JSON definition file.

        Args:
            json_path (str): The path to the JSON file generated by t2_make_poly.py.
        """
        super().__init__()
        print(f"  - Creating polynomial approximation module from {Path(json_path).name}")

        with open(json_path, 'r') as f:
            data = json.load(f)

        # Get polynomial range, order, and coefficients
        self.poly_range = data['poly_range']  # e.g., [-4, 4]
        self.order = data['order']
        coeffs = data['coefficients']

        # Store coefficients in a tensor buffer for automatic device placement.
        # The coefficients are loaded in the order p_n, p_{n-1}, ..., p_0,
        # which is the standard format for polynomial evaluation routines.
        poly_coeffs_tensor = torch.zeros(self.order + 1)
        for i in range(self.order + 1):
            key = f"p{self.order - i}"
            if key in coeffs:
                poly_coeffs_tensor[i] = coeffs[key]
        
        # Register as a buffer so it's moved to the correct device with .to(device)
        self.register_buffer('poly_coeffs', poly_coeffs_tensor)

        # Get the behavior for the linear tails of the function
        self.lower_tail_value = data['lower_tail']['value']
        self.upper_tail_slope = data['upper_tail']['slope']
        self.upper_tail_intercept = data['upper_tail']['intercept']

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Applies the piecewise polynomial GELU approximation to the input tensor.
        """
        # Create boolean masks to identify which elements fall into which region
        lower_mask = x < self.poly_range[0]
        upper_mask = x > self.poly_range[1]
        # The polynomial mask covers everything not in the lower or upper tails
        poly_mask = ~lower_mask & ~upper_mask

        # Initialize the output tensor with the same shape as the input
        y = torch.empty_like(x)

        # Apply the functions for each region using the masks
        # 1. Lower tail (y = 0)
        y[lower_mask] = self.lower_tail_value
        
        # 2. Upper tail (y = x)
        y[upper_mask] = self.upper_tail_slope * x[upper_mask] + self.upper_tail_intercept

        # 3. Polynomial region (-4 <= x <= 4)
        x_poly = x[poly_mask]
        if x_poly.numel() > 0:
            # Use Horner's method for efficient and stable polynomial evaluation
            # y = c_n*x^n + c_{n-1}*x^{n-1} + ... = ((c_n*x + c_{n-1})*x + ...)
            poly_output = self.poly_coeffs[0]
            for i in range(1, self.order + 1):
                poly_output = poly_output * x_poly + self.poly_coeffs[i]
            y[poly_mask] = poly_output
            
        return y

if __name__ == '__main__':
    """
    A self-contained example to demonstrate and test the PolyGelu module.
    This will create a dummy JSON file and run a test tensor through the module.
    """
    print("--- Testing PolyGelu Module ---")
    
    # Create a dummy json file for testing purposes
    dummy_data = {
        "function": "gelu_poly_approx",
        "order": 7,
        "poly_range": [-4, 4],
        "coefficients": {
            "p7": 0.0003, "p6": 0.0000, "p5": 0.0058, "p4": 0.0000,
            "p3": 0.0561, "p2": 0.0000, "p1": 0.5000, "p0": 0.0000
        },
        "lower_tail": {"type": "constant", "value": 0.0},
        "upper_tail": {"type": "linear", "slope": 1.0, "intercept": 0.0}
    }
    dummy_dir = Path("dst_poly")
    dummy_dir.mkdir(exist_ok=True)
    dummy_path = dummy_dir / "dummy_poly_gelu_7_order.json"
    with open(dummy_path, 'w') as f:
        json.dump(dummy_data, f, indent=4)
    print(f"Created dummy config file at: {dummy_path}")

    # Instantiate the module
    poly_gelu = PolyGelu(str(dummy_path))
    print("\nModule instantiated successfully.")
    print("Loaded Coefficients:", poly_gelu.poly_coeffs)

    # Test with a sample tensor covering all three regions
    x_test = torch.tensor([-6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0], dtype=torch.float32)
    y_test = poly_gelu(x_test)
    
    print("\n--- CPU Test ---")
    print(f"Input tensor:  {x_test}")
    print(f"Output tensor: {y_test}")

    # Verify that the outputs match the expected behavior
    # Expected: [0.0 (lower), poly(-4), poly(-2), poly(0), poly(2), poly(4), 6.0 (upper)]
    print("\nVerification:")
    print(f"x=-6.0 -> y={y_test[0]:.4f} (Expected: 0.0)")
    print(f"x=6.0  -> y={y_test[-1]:.4f} (Expected: 6.0)")

    # Test on GPU if available
    if torch.cuda.is_available():
        print("\n--- GPU Test ---")
        device = torch.device("cuda")
        poly_gelu_gpu = poly_gelu.to(device)
        x_test_gpu = x_test.to(device)
        y_test_gpu = poly_gelu_gpu(x_test_gpu)
        
        print(f"Input tensor (GPU):  {x_test_gpu.cpu()}")
        print(f"Output tensor (GPU): {y_test_gpu.cpu()}")
        print(f"Module buffers are on device: '{poly_gelu_gpu.poly_coeffs.device}'")
